"""Initial migration

Revision ID: 5ee13a0f45ba
Revises: 
Create Date: 2026-05-29 20:19:13.300360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee13a0f45ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=True),
    sa.Column('draft_id', sa.String(length=16), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_entries',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('issue_tags', sa.JSON(), nullable=True),
    sa.Column('correction_plan', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_avoided', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_topic'), 'memory_entries', ['topic'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('time_source', sa.String(length=50), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('composite_score', sa.Integer(), nullable=True),
    sa.Column('timeliness_score', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trends')
    op.drop_index(op.f('ix_memory_entries_topic'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_table('generation_results')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
