"""add celery fields to generation_jobs

Revision ID: 8f3bb9584a0c
Revises: 7410015efd2f
Create Date: 2026-05-31 19:26:34.606498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3bb9584a0c'
down_revision: Union[str, Sequence[str], None] = '7410015efd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('dead_letter', sa.Boolean(), nullable=True))
    op.add_column('generation_jobs', sa.Column('celery_task_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'celery_task_id')
    op.drop_column('generation_jobs', 'dead_letter')
    op.drop_column('generation_jobs', 'max_retries')
    op.drop_column('generation_jobs', 'retry_count')
    # ### end Alembic commands ###
